### ISSUE TITLE
Add description of community

### ISSUE THREAD

**Issue by mary-grace** [camunda-community-hub/devrel-team#1]
Who do we serve? Who's part of the Camunda community?

**Comment by celanthe** [comment]
Hi @mary-grace! I just wanted to circle back on this and see if we wanted to leave this issue open, and who it might be able to be re-assigned to? Thanks so much!

**Comment by akeller** [comment]
@celanthe please assign to @mary-grace

**Comment by mary-grace** [comment]
I'm comfortable closing this out for now. It's not necessary at the moment and if we want to revisit in the future, we can do so.
